### PR TITLE
feat: initialize shadcn/ui with button component

### LINKED ISSUE #11: Add chadcn/ui
Add [chadcn/ui](https://ui.shadcn.com/docs) to project.

Update the project UI to use chadcn/ui

### PR DESCRIPTION
**Pull request by rockingrohit9639**
Fix #11

### CODE REVIEW

**Comment by RuanAragao** [comment]
Hey @rockingrohit9639, thanks for the PR! Can you update de UI (form) to use shadcn/ui components?

**Comment by rockingrohit9639** [comment]
> Hey @rockingrohit9639, thanks for the PR! Can you update de UI (form) to use shadcn/ui components?

Yeah sure @RuanAragao

**Comment by rockingrohit9639** [comment]
Hey @RuanAragao I have updated the form UI. It looks like this now.
image

**Comment by RuanAragao** [comment]
Thank you very much @rockingrohit9639!

**Pull request merged**
